version: "3.9"
services:
  ripper:
    container_name: ripper
    image: overlydev/streamripper-docker:latest
    volumes:
      - ./songs:/songs
    environment:
      URL: "http://prem1.di.fm:80/chillstep_hi?69040976d1ea73ad"
      USER_AGENT: "Don't worry about it :)"
